-- ContextGrade: AI Decision Reports
-- On-demand per-client, per-category decision.md compilation.
-- Generated by dashboard staff/admin; not triggered on every decision log.

CREATE TYPE "ai_report_status" AS ENUM ('PENDING', 'GENERATING', 'COMPLETED', 'FAILED');

CREATE TABLE "ai_decision_reports" (
    "id"            UUID            NOT NULL DEFAULT gen_random_uuid(),
    "client_id"     INTEGER         NOT NULL,
    "category_id"   UUID            NOT NULL,
    "title"         TEXT,
    "content"       TEXT,
    "status"        "ai_report_status" NOT NULL DEFAULT 'PENDING',
    "decision_count" INTEGER,
    "agent_model"   TEXT,
    "triggered_by"  INTEGER,
    "generated_at"  TIMESTAMPTZ(6),
    "created_at"    TIMESTAMPTZ(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"    TIMESTAMPTZ(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_decision_reports_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ai_decision_reports_client_id_idx"
    ON "ai_decision_reports"("client_id");

CREATE INDEX "ai_decision_reports_client_id_category_id_idx"
    ON "ai_decision_reports"("client_id", "category_id");

CREATE INDEX "ai_decision_reports_status_idx"
    ON "ai_decision_reports"("status");

ALTER TABLE "ai_decision_reports"
    ADD CONSTRAINT "ai_decision_reports_client_id_fkey"
    FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ai_decision_reports"
    ADD CONSTRAINT "ai_decision_reports_category_id_fkey"
    FOREIGN KEY ("category_id") REFERENCES "client_context_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ai_decision_reports"
    ADD CONSTRAINT "ai_decision_reports_triggered_by_fkey"
    FOREIGN KEY ("triggered_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
